<a href="https://colab.research.google.com/github/kim-heesu/DataAnalysis/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_5%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 5강 - 데이터 저장

## 5-1 CSV 형식 저장

In [5]:
import pandas as pd

data = {
    'student_id': [101, 102, 103, 104, 105],
    'database_score': [85, 76, 92, 63, 88],
    'cloudcomputing_score': [78, 82, 95, 70, 84],
    'python_score': [92, 78, 85, 75, 91],
    'watch_rate': [0.95, 0.87, 0.99, 0.80, 0.93]
}
## DataFrame 생성
df = pd.DataFrame(data)
df
## CSV 형식 저장
df.to_csv('student_analysis.csv', encoding='utf-8', index=False)

## 5-2 JSON 형식 저장

In [10]:
### 라이브러리 임포트
import json
import pandas as pd

data = {
    "이름": "홍길동",
    "나이": 25,
    "거주지": "서울",
    "관심사": ["프로그래밍", "데이터 분석", "여행"]
}

## json.dump를 이용한 저장
with open('output.json', mode='w', encoding='utf-8') as f :
    json.dump(data,f,indent=4,ensure_ascii=False)

## DataFrame을 이용한 저장
df= pd.DataFrame(data)
df.to_json('output_df.json', orient='records', indent=4, force_ascii=False)

## 5-3 Pandas Dataframe 데이터 추출

In [18]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터학", "경영학", "농학", "교육학", "영어영문학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)
df
## DataFrame 인덱스 출력
print(df.index)

## DataFrame 컬럼 출력
print(df.columns)

## DataFrame 행 출력
print(df.values.tolist()) # Numpy 배열 -> 파이썬의 일반 리스트로 반환
print(df.values) #DataFrame의 값들을 Numpy 배열로 반환

## DataFrame 값 출력
print(df.values.flatten())

RangeIndex(start=0, stop=5, step=1)
Index(['이름', '학년', '학점', '학과', '동아리'], dtype='object')
[['김철수', 1, 4.2, '컴퓨터학', '프로그래밍'], ['이영희', 2, 3.8, '경영학', '독서토론'], ['박민수', 3, 4.5, '농학', '로봇공학'], ['최지훈', 4, 3.9, '교육학', '봉사활동'], ['정소희', 2, 3.5, '영어영문학', '음악감상']]
[['김철수' 1 4.2 '컴퓨터학' '프로그래밍']
 ['이영희' 2 3.8 '경영학' '독서토론']
 ['박민수' 3 4.5 '농학' '로봇공학']
 ['최지훈' 4 3.9 '교육학' '봉사활동']
 ['정소희' 2 3.5 '영어영문학' '음악감상']]
['김철수' 1 4.2 '컴퓨터학' '프로그래밍' '이영희' 2 3.8 '경영학' '독서토론' '박민수' 3 4.5 '농학'
 '로봇공학' '최지훈' 4 3.9 '교육학' '봉사활동' '정소희' 2 3.5 '영어영문학' '음악감상']

## 5-4 DataFrame 생성 방법

In [21]:
import pandas as pd
import json

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## 딕셔너리, csv, json으로 부터 DataFrame 생성
df1 = pd.DataFrame.from_dict(data)
df2 = pd.read_csv('students.csv')
df3 = pd.read_json('students.json')

## 세가지 방법 결과 비교
print(df1.shape)
print(df2.shape)
print(df3.shape)

(5, 5)
(5, 5)
(5, 5)

## 5-5 DataFrame 저장 방법

In [23]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

## Dataframe 생성
df=pd.DataFrame(data)

## CSV, JSON 형식으로 저장
df.to_csv('students_scores.csv')
df.to_json('students_scores.json')

## HTML 형식으로 저장
html_table = df.to_html()
print(html_table)

with open('html_table.html',mode='w') as f :
    f.write(html_table)

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>이름</th>
      <th>학년</th>
      <th>학점</th>
      <th>학과</th>
      <th>동아리</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>김철수</td>
      <td>1</td>
      <td>4.2</td>
      <td>컴퓨터공학</td>
      <td>프로그래밍</td>
    </tr>
    <tr>
      <th>1</th>
      <td>이영희</td>
      <td>2</td>
      <td>3.8</td>
      <td>경영학</td>
      <td>독서토론</td>
    </tr>
    <tr>
      <th>2</th>
      <td>박민수</td>
      <td>3</td>
      <td>4.5</td>
      <td>전자공학</td>
      <td>로봇공학</td>
    </tr>
    <tr>
      <th>3</th>
      <td>최지훈</td>
      <td>4</td>
      <td>3.9</td>
      <td>의학</td>
      <td>봉사활동</td>
    </tr>
    <tr>
      <th>4</th>
      <td>정소희</td>
      <td>2</td>
      <td>3.5</td>
      <td>심리학</td>
      <td>음악감상</td>
    </tr>
  </tbody>
</table>

## 5-6 실습 시나리오

## 데이터 수집

In [25]:
import requests

url = "http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty"
api_key = ''

params = {
    'serviceKey': api_key,
    'returnType': 'json',
    'numOfRows': '100',
    'pageNo': '1',
    'sidoName': '서울',
    'ver': '1.0'
}

## 데이터 수집
response = requests.get(url, params=params)

## 호출 성공/실패 출력
print(response.json())

{'response': {'body': {'totalCount': 40, 'items': [{'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '강남구', 'pm10Grade': '2', 'o3Value': '0.062'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.003', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '33', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '서초구', 'pm10Grade': '2', 'o3Value': '0.056'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '40', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '도산대로', 'pm10Grade': '2', 'o3Value': '0.056'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '43', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '1', 'pm10Value': '30', 'khaiGrade': '1', 'pm25Value': '19', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.026', 'stationName': '강남대로', 'pm10Grade': '1', 'o3Value': '0.020'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '40', 'khaiGrade': '2', 'pm25Value': '24', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '송파구', 'pm10Grade': '2', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '강동구', 'pm10Grade': '2', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '천호대로', 'pm10Grade': '2', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '58', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '32', 'khaiGrade': '2', 'pm25Value': '24', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '금천구', 'pm10Grade': '1', 'o3Value': '0.039'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '63', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.012', 'stationName': '시흥대로', 'pm10Grade': '2', 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '33', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '강북구', 'pm10Grade': '2', 'o3Value': '0.056'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '양천구', 'pm10Grade': '2', 'o3Value': '0.058'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '19', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.007', 'stationName': '노원구', 'pm10Grade': '2', 'o3Value': '0.053'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '63', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '화랑로', 'pm10Grade': '2', 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '71', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '중구', 'pm10Grade': '1', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '67', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '34', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '한강대로', 'pm10Grade': '2', 'o3Value': '0.050'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '71', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '34', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '종로구', 'pm10Grade': '2', 'o3Value': '0.055'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '청계천로', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '33', 'khaiGrade': '2', 'pm25Value': '19', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '종로', 'pm10Grade': '2', 'o3Value': '0.050'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '43', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '용산구', 'pm10Grade': '2', 'o3Value': '0.051'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '71', 'so2Value': '0.003', 'coValue': '0.6', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '43', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '광진구', 'pm10Grade': '2', 'o3Value': '0.054'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '성동구', 'pm10Grade': '1', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '63', 'so2Value': '0.003', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '강변북로', 'pm10Grade': '2', 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '26', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '중랑구', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '25', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '동대문구', 'pm10Grade': '2', 'o3Value': '0.053'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '67', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '홍릉로', 'pm10Grade': '2', 'o3Value': '0.050'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '17', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.004', 'stationName': '성북구', 'pm10Grade': '2', 'o3Value': '0.045'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.001', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '34', 'khaiGrade': '2', 'pm25Value': '18', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.011', 'stationName': '정릉로', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '29', 'khaiGrade': '2', 'pm25Value': '14', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.002', 'stationName': '도봉구', 'pm10Grade': '1', 'o3Value': '0.062'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '68', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '32', 'khaiGrade': '2', 'pm25Value': '17', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '은평구', 'pm10Grade': '2', 'o3Value': '0.051'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '65', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '28', 'khaiGrade': '2', 'pm25Value': '18', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '서대문구', 'pm10Grade': '2', 'o3Value': '0.047'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '66', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '마포구', 'pm10Grade': '2', 'o3Value': '0.048'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '72', 'so2Value': '0.002', 'coValue': '0.5', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '20', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.018', 'stationName': '신촌로', 'pm10Grade': '2', 'o3Value': '0.044'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.003', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '21', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '강서구', 'pm10Grade': '2', 'o3Value': '0.049'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '43', 'khaiGrade': '2', 'pm25Value': '28', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.013', 'stationName': '공항대로', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '74', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '30', 'khaiGrade': '2', 'pm25Value': '13', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '1', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.005', 'stationName': '구로구', 'pm10Grade': '1', 'o3Value': '0.059'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '69', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '35', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '영등포구', 'pm10Grade': '2', 'o3Value': '0.052'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '62', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '38', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.016', 'stationName': '영등포로', 'pm10Grade': '2', 'o3Value': '0.044'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.002', 'coValue': '0.3', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '36', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.009', 'stationName': '동작구', 'pm10Grade': '1', 'o3Value': '0.053'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '64', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '37', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.015', 'stationName': '동작대로 중앙차로', 'pm10Grade': '2', 'o3Value': '0.046'}, {'so2Grade': '1', 'coFlag': None, 'khaiValue': '70', 'so2Value': '0.000', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '40', 'khaiGrade': '2', 'pm25Value': '22', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.010', 'stationName': '관악구', 'pm10Grade': '2', 'o3Value': '0.054'}], 'pageNo': 1, 'numOfRows': 100}, 'header': {'resultMsg': 'NORMAL_CODE', 'resultCode': '00'}}}

## 데이터 프레임 생성

In [30]:
import pandas as pd

## requests로부터 response, body, item 항목 읽기
data = response.json()['response']['body']['items']
print(type(data))
print(data[0])

df = pd.DataFrame(data)
df

<class 'list'>
{'so2Grade': '1', 'coFlag': None, 'khaiValue': '77', 'so2Value': '0.002', 'coValue': '0.4', 'pm25Flag': None, 'pm10Flag': None, 'o3Grade': '2', 'pm10Value': '39', 'khaiGrade': '2', 'pm25Value': '23', 'sidoName': '서울', 'no2Flag': None, 'no2Grade': '1', 'o3Flag': None, 'pm25Grade': '2', 'so2Flag': None, 'dataTime': '2026-09-27 24:00', 'coGrade': '1', 'no2Value': '0.008', 'stationName': '강남구', 'pm10Grade': '2', 'o3Value': '0.062'}

,so2Grade,coFlag,khaiValue,so2Value,coValue,pm25Flag,pm10Flag,o3Grade,pm10Value,khaiGrade,...,no2Grade,o3Flag,pm25Grade,so2Flag,dataTime,coGrade,no2Value,stationName,pm10Grade,o3Value
0,1,None,77,0.002,0.4,None,None,2,39,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,강남구,2,0.062
1,1,None,72,0.003,0.3,None,None,2,33,2,...,1,None,2,None,2026-09-27 24:00,1,0.007,서초구,2,0.056
2,1,None,72,0.003,0.5,None,None,2,40,2,...,1,None,2,None,2026-09-27 24:00,1,0.010,도산대로,2,0.056
3,1,None,43,0.002,0.5,None,None,1,30,1,...,1,None,1,None,2026-09-27 24:00,1,0.026,강남대로,1,0.020
4,1,None,70,0.002,0.3,None,None,2,40,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,송파구,2,0.054
5,1,None,69,0.003,0.5,None,None,2,39,2,...,1,None,2,None,2026-09-27 24:00,1,0.007,강동구,2,0.052
6,1,None,70,0.002,0.4,None,None,2,39,2,...,1,None,2,None,2026-09-27 24:00,1,0.010,천호대로,2,0.054
7,1,None,58,0.003,0.5,None,None,2,32,2,...,1,None,2,None,2026-09-27 24:00,1,0.012,금천구,1,0.039
8,1,None,63,0.003,0.4,None,None,2,38,2,...,1,None,2,None,2026-09-27 24:00,1,0.012,시흥대로,2,0.045
9,1,None,72,0.002,0.3,None,None,2,33,2,...,1,None,2,None,2026-09-27 24:00,1,0.005,강북구,2,0.056
10,1,None,74,0.002,0.3,None,None,2,36,2,...,1,None,2,None,2026-09-27 24:00,1,0.007,양천구,2,0.058
11,1,None,70,0.002,0.3,None,None,2,35,2,...,1,None,2,None,2026-09-27 24:00,1,0.007,노원구,2,0.053
12,1,None,63,0.002,0.4,None,None,2,39,2,...,1,None,2,None,2026-09-27 24:00,1,0.015,화랑로,2,0.045
13,1,None,71,0.002,0.4,None,None,2,35,2,...,1,None,2,None,2026-09-27 24:00,1,0.009,중구,1,0.054
14,1,None,67,0.002,0.5,None,None,2,34,2,...,1,None,2,None,2026-09-27 24:00,1,0.015,한강대로,2,0.050
15,1,None,71,0.002,0.4,None,None,2,34,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,종로구,2,0.055
16,1,None,64,0.002,0.4,None,None,2,38,2,...,1,None,2,None,2026-09-27 24:00,1,0.010,청계천로,2,0.046
17,1,None,68,0.002,0.4,None,None,2,33,2,...,1,None,2,None,2026-09-27 24:00,1,0.009,종로,2,0.050
18,1,None,68,0.002,0.3,None,None,2,43,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,용산구,2,0.051
19,1,None,71,0.003,0.6,None,None,2,43,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,광진구,2,0.054
20,1,None,69,0.002,0.4,None,None,2,36,2,...,1,None,1,None,2026-09-27 24:00,1,0.009,성동구,1,0.052
21,1,None,63,0.003,0.5,None,None,2,39,2,...,1,None,2,None,2026-09-27 24:00,1,0.016,강변북로,2,0.045
22,1,None,64,0.002,0.4,None,None,2,35,2,...,1,None,2,None,2026-09-27 24:00,1,0.010,중랑구,2,0.046
23,1,None,72,0.002,0.4,None,None,2,36,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,동대문구,2,0.053
24,1,None,67,0.002,0.4,None,None,2,35,2,...,1,None,2,None,2026-09-27 24:00,1,0.015,홍릉로,2,0.050
25,1,None,64,0.003,0.4,None,None,2,38,2,...,1,None,2,None,2026-09-27 24:00,1,0.004,성북구,2,0.045
26,1,None,64,0.001,0.4,None,None,2,34,2,...,1,None,2,None,2026-09-27 24:00,1,0.011,정릉로,2,0.046
27,1,None,77,0.003,0.4,None,None,2,29,2,...,1,None,1,None,2026-09-27 24:00,1,0.002,도봉구,1,0.062
28,1,None,68,0.003,0.4,None,None,2,32,2,...,1,None,2,None,2026-09-27 24:00,1,0.005,은평구,2,0.051
29,1,None,65,0.003,0.4,None,None,2,28,2,...,1,None,2,None,2026-09-27 24:00,1,0.009,서대문구,2,0.047
30,1,None,66,0.002,0.3,None,None,2,36,2,...,1,None,2,None,2026-09-27 24:00,1,0.010,마포구,2,0.048
31,1,None,72,0.002,0.5,None,None,2,38,2,...,1,None,2,None,2026-09-27 24:00,1,0.018,신촌로,2,0.044
32,1,None,69,0.003,0.4,None,None,2,36,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,강서구,2,0.049
33,1,None,74,0.002,0.4,None,None,2,43,2,...,1,None,2,None,2026-09-27 24:00,1,0.013,공항대로,2,0.046
34,1,None,74,0.002,0.3,None,None,2,30,2,...,1,None,1,None,2026-09-27 24:00,1,0.005,구로구,1,0.059
35,1,None,69,0.002,0.4,None,None,2,35,2,...,1,None,2,None,2026-09-27 24:00,1,0.008,영등포구,2,0.052
36,1,None,62,0.002,0.4,None,None,2,38,2,...,1,None,2,None,2026-09-27 24:00,1,0.016,영등포로,2,0.044
37,1,None,70,0.002,0.3,None,None,2,36,2,...,1,None,2,None,2026-09-27 24:00,1,0.009,동작구,1,0.053
38,1,None,64,0.002,0.4,None,None,2,37,2,...,1,None,2,None,2026-09-27 24:00,1,0.015,동작대로 중앙차로,2,0.046
39,1,None,70,0.000,0.4,None,None,2,40,2,...,1,None,2,None,2026-09-27 24:00,1,0.010,관악구,2,0.054

## 다양항 형식으로 데이터 저장

In [33]:
df.to_csv('air_pollution.csv', index=False, encoding='utf-8')

## JSON 형식 데이터 저장
df.to_json('air_pollution.json', indent=4, force_ascii=False)

## EXCEL 형식 데이터 저장
df.to_excel('air_pollution.xlsx', index=False)

## HTML 형식 데이터 저장
df.to_html('air_pollution.html')